version: '3.8'

services:
  pocketmine:
    networks:
      - bdd
    build:
      context: ./pocketmine
    image: server
    container_name: pocketmine-server
    ports:
      - "19132:19132/udp"
    environment:
      MYSQL_HOST: mariadb
      MYSQL_PORT: 5432
      MYSQL_DB: mc_server
      MYSQL_USER: mc_user
      MYSQL_PASSWORD: mc_password
    volumes:
      - "./pocketmine/data/worlds:/pocketmine/worlds/"
      - "./pocketmine/data/players:/pocketmine/players/"
    depends_on:
      - mariadb

  mariadb:
    networks:
      - bdd
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mc_server
      MYSQL_USER: mc_user
      MYSQL_PASSWORD: mc_password
    volumes:
      - ./data/db:/var/lib/mysql

  phpmyadmin:
    networks:
      - bdd
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:8080"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root

  nextjs:
    networks:
      - bdd
    build: ./web
    container_name: nextjs
    environment:
      - DB_URL=mariadb://mc_user:mc_password@mariadb:5432/mc_server
    depends_on:
      - mariadb

  discordbot:
    networks:
      - bdd
    build: ./discord-bot
    container_name: discordbot
    environment:
      - DB_URL=mariadb://mc_user:mc_password@mariadb:5432/mc_server
    depends_on:
      - mariadb

  nginx:
    networks:
      - bdd
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./server-web/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs

networks:
  bdd:
